### ISSUE TITLE
AttributeError: 'MegatronGPTModel' object has no attribute 'decoder'

### ISSUE THREAD

**Issue by lianghsun** [NVIDIA/NeMo#10034]
#### Description

I am retraining a LLaMA3 model. Due to the limited size of my dataset, I attempted to use `freeze_updates` as referenced in the [NVIDIA NeMo documentation](https://docs.nvidia.com/nemo-framework/user-guide/latest/nemotoolkit/core/neural_modules.html#dynamic-layer-freezing). My configuration is as follows:

```yaml
freeze_updates:
  enabled: true  # set to false if you want to disable freezing
  modules:   # list all of the modules you want to have freezing logic for
    decoder: 100
```
However, I encountered the following error:
```
AttributeError: 'MegatronGPTModel' object has no attribute 'decoder'
```

I also tried changing decoder to `encoder` or `joint`, but I still faced errors. I would like to ask how to properly configure this setting?

Additionally, within the NeMo framework, is it possible to freeze specific layers, such as only the attention layer? If so, how can I achieve this? Thanks!
