### ISSUE TITLE
When training ASR models, it saves .nemo 2 times in a row

### ISSUE THREAD

**Issue by AudranBert** [NVIDIA/NeMo#10798]
**Describe the bug**

When training ASR models, it calls "on_save_checkpoint" 2 times in a row. It is unnecessary and can take some time. It is visible when you use "always_save_nemo": True and "save_last": True because you will see the logs below:

```log
[NeMo I 2024-10-08 14:35:07 nemo_model_checkpoint:247] New .nemo model saved to:nemo_experiments/TEST/checkpoints/TEST.nemo
[NeMo I 2024-10-08 14:35:18 nemo_model_checkpoint:321] nemo_experiments/TEST/checkpoints/TEST.nemo already exists, moving existing checkpoint to nemo_experiments/TEST/checkpoints/TEST-v1.nemo
[NeMo I 2024-10-08 14:35:37 nemo_model_checkpoint:247] New .nemo model saved to: nemo_experiments/TEST/checkpoints/TEST.nemo
[NeMo I 2024-10-08 14:35:37 nemo_model_checkpoint:249] Removing old .nemo backup nemo_experiments/TEST/checkpoints/TEST-v1.nemo
```

**Steps/Code to reproduce bug**

I think you can use [this](https://github.com/NVIDIA/NeMo/blob/ff97c70fc9d7a0050c947b9008372bcf2e6f3b48/examples/asr/asr_ctc/speech_to_text_ctc.py) to try since it is what I'm based on.
I use the following options in the exp_manager:

```yaml
exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  create_early_stopping_callback: False
  early_stopping_callback_params:
    check_finite: False
    patience: 5
    mode: "min"
    monitor: "val_loss"
  checkpoint_callback_params:
    every_n_epochs: null
    every_n_train_steps: 8
    monitor: train_loss
    save_top_k: -1
    always_save_nemo: true
    save_last: true
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
```

**Expected behavior**

It should not save the .nemo 2 times in a row. Or it should name with "-last.nemo" too.

**Environment details**

I locally installed NeMo with pip and I have a Nvidia GPU
