### ISSUE TITLE
How can I get stt_en_fastconformer_ctc_small pretrain model??

### ISSUE THREAD

**Issue by PhamDangNguyen** [NVIDIA/NeMo#11204]
I fill "stt_en_fastconformer_ctc_small" in init_from_pretrained_model but i get an error "not found" the "stt_en_fastconformer_ctc_small"
```yaml
name: "FastConformer-CTC-BPE"
# name: "model STT N test"

init_from_pretrained_model: "stt_en_fastconformer_ctc_small" 

model:
  sample_rate: 16000
  log_prediction: true # enables logging sample predictions in the output during training
  ctc_reduction: 'mean_volume'
  skip_nan_grad: false
  model_defaults:
    pred_hidden: 320
    joint_hidden: 320

  train_ds:
    manifest_filepath: /home/team_voice/STT_pdnguyen/finetune-fast-conformer_14m/metadata_train/fubon_add_all_data_train_10_10_2024.json
    sample_rate: ${model.sample_rate}
    batch_size: 1 # you may increase batch_size if your memory allows
    shuffle: true
    num_workers: 32
    pin_memory: true
    max_duration: 20 # it is set for LibriSpeech, you may need to update it for your dataset
    min_duration: 0.3
    # tarred datasets
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    # bucketing params
    bucketing_strategy: "fully_randomized"
    bucketing_batch_size: null
```
