### ISSUE TITLE
Titanet-Large training: Multi-node, Multi-gpu

### ISSUE THREAD

**Issue by ukemamaster** [NVIDIA/NeMo#12936]
Hi, i am using this script `python NeMo/examples/speaker_tasks/recognition/speaker_reco.py` to train the titanet-large model, with a **Single-node, Multi-gpu** setup. However, for a **Multi-node, Multi-gpu** setup i get the following warining: 
```
[NeMo E 2025-04-08 13:17:51 exp_manager:833] You are running multi-node training without SLURM handling the processes. Please note that this is not tested in NeMo and could result in errors.
```
The trainer config looks like: 
```
trainer:
  devices: 8 # number of gpus (original titanet-large was trained on 4 nodes with 8 gpus each)
  max_epochs: 250
  max_steps: -1 # computed at runtime if not set
  num_nodes: 2
  accelerator: gpu
  strategy: ddp
  deterministic: True
  enable_checkpointing: False
  logger: False
  log_every_n_steps: 1  # Interval of logging.
  val_check_interval: 1.0  # Set to 0.25 to check 4 times per epoch, or an int for number of iterations
  gradient_clip_val: 1.0

```
Could you please suggest an example on how to run a **Multi-node, Multi-gpu** experiment?
