### ISSUE TITLE
Key Error when trying to Inference using Fine Tuned llama4 model

### ISSUE THREAD

**Issue by kanic1111** [NVIDIA/NeMo#13656]
**Describe the bug**

when try to run the generate(Inference) script with Finetune checkpoint for llama4 it will shows the keyerror: module.language_model.decoder.layers.self_attention.linear_proj.weight from model not in state dict

![Image](https://github.com/user-attachments/assets/7094b24f-bc45-4060-ac42-1bcf49350b25)

**doesn't shows the same error with model that are not finetuned**

**Steps/Code to reproduce bug**

Please list *minimal* steps or code snippet for us to be able to reproduce the bug.

```python=
from nemo.collections.vlm.inference.base import _setup_trainer_and_restore_model

path = Path(local_model_path) # with finetuned model path
model: io.TrainerContext = io.load_context(path=ckpt_to_context_subdir(path), subpath="model")
_setup_trainer_and_restore_model(path=path, trainer=trainer, model=model) # this is when it shows the key error
```

A  helpful guide on on how to craft a minimal bug report  http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. 

**Expected behavior**

should be able to inference with Finetuned model like in [Nemo 2.0 llama4 documentation](https://docs.nvidia.com/nemo-framework/user-guide/latest/vlms/llama4.html) says

**Environment overview (please complete the following information)**

 - Environment location: kubernetes 1.28.15
 - Method of NeMo install: [using Nvidia Nemo dev container image with pip install transformers==4.51.0  && git clone  NeMo repository]. Please specify exact commands you used to install.
yaml is here:
```yaml=
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nemo
spec:
  replicas: 8
  selector:
    matchLabels:
      app: nemo
  template:
    metadata:
      name: nemo
      labels:
        app: nemo
    spec:
      containers:
      - name: nemo
        image: nvcr.io/nvidia/nemo:dev
        command: ["sleep", "infinity"]
        volumeMounts:
        - name: workspace
          mountPath: /nemo-workspace
        - mountPath: /dev/shm
          name: dev-shm
        env:
        - name: NEMO_MODELS_CACHE
          value: "/nemo-workspace/.cache"
        - name: HF_HOME
          value: "/nemo-workspace/hf/cache"
        - name: HUGGINGFACE_HUB_CACHE
          value: "/nemo-workspace/hf/hub_cache"
        resources:
          limits:
            nvidia.com/gpu: 2
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: nemo-workspace
      - emptyDir:
          medium: "Memory"
          sizeLimit: "64Gi"
        name: dev-shm
```

it's for testing so i run code in pod manually 

**Environment details**

If NVIDIA docker image is used you don't need to specify these.
Otherwise, please provide:
- OS version
- PyTorch version
- Python version

**Additional context**

Example: GPU model
8 node  each node with Nvidia A30 x2
Network: 25Gbps 
Storage: Ceph with 30TB capabilities
