### ISSUE TITLE
Cannot beamdecoding without LM

### ISSUE THREAD

**Issue by Austin1207** [NVIDIA/NeMo#13780]
I try to use fastconformer_ctc model with beamdecoding but not greedy, I add the following terms in the yaml

```
  decoding:
    strategy: "beam"
    beam:
      beam_size: 4
      search_type: "default"
      preserve_alignments: False
      compute_timestamps: False
      return_best_hypothesis: True

      beam_alpha: 0.0
      beam_beta:  0.0
```

But it shows the following Error:
`FileNotFoundError: KenLM binary file not found at : None. Please set a valid path in the decoding config.`

I want to ask that if I could use beamdecoding without LM?
