### ISSUE TITLE
Silent failure: no warning when user-supplied lm_checkpoint file does not exist

### ISSUE THREAD

**Issue by carolmanderson** [NVIDIA/NeMo#2599]
**Describe the bug**
I'm using the intent/slot model and supplying my own language model checkpoint and config (for a 2-layer version of DistilBert), as follows:

```
  language_model:
    max_seq_length: 50
    pretrained_model_name: distilbert-base-uncased
    lm_checkpoint: /home/carola/Documents/models/distillation/atis_snips_pred_2L.ckpt
    config_file: /home/carola/Documents/configs/language_models/joc_bert_2l.json
    config: null
```

During normal training this is logged:

```
[NeMo I 2021-08-03 13:11:43 bert_module:54] Restoring weights from /home/carola/Documents/models/distillation/atis_snips_pred_2L.ckpt
[NeMo I 2021-08-03 13:11:43 bert_module:82] Weights for DistilBertEncoder restored from /home/carola/Documents/models/distillation/atis_snips_pred_2L.ckpt
```

However, if I mispell the checkpoint file or otherwise provide a file that doesn't exist, like this:

```
 language_model:
    max_seq_length: 50
    pretrained_model_name: distilbert-base-uncased
    lm_checkpoint: /home/carola/Documents/models/distillation/my_fake_file.ckpt  # file that does not exist
    config_file: /home/carola/Documents/configs/language_models/joc_bert_2l.json  # this one does exist
    config: null
```

Then the only sign that something is wrong is that the "Restoring weights" lines are missing from the log, which is hard to notice. The model also performs poorly. Otherwise, training proceeds apparently normally and the resulting saved models have the expected number of layers/parameters, as specified by the config I provided. I guess the weights must be getting initialized from the default 6-layer DistilBert checkpoint, which should not happen.

**Expected behavior**
An exception should be raised if a checkpoint file is provided in the config but does not exist.

**Environment details**
nemo-toolkit 1.2.0 (fresh install via reinstall.sh)
Ubuntu 18.04
python 3.7
PyTorch 1.9.0+cu102
