### ISSUE TITLE
from_pretrained() does not update configuration in exp_manager

### ISSUE THREAD

**Issue by piraka9011** [NVIDIA/NeMo#3372]
**Describe the bug**

When fine tuning from a NeMo model (ex. stt_en_cn1024), the exp_manager's cfg is not updated properly.
I can see that in my run the model uses one config, but WandB reports another.

This issue did not occur in v1.4.0 and happened after I upgraded to v1.5.0.
Maybe it has to do with order of operations? See below.

**Steps/Code to reproduce bug**

```py
import pytorch_lightning as pl
from nemo.collections.asr.models import EncDecCTCModelBPE
from nemo.core.config import hydra_runner
from nemo.utils.exp_manager import exp_manager

@hydra_runner(config_path="conf/citrinet/", config_name="config")
def main(cfg):
    trainer = pl.Trainer(**cfg.trainer)
    log_dir = exp_manager(trainer, cfg.get("exp_manager", None))
    asr_model = EncDecCTCModelBPE.from_pretrained(model_name=cfg.init_from_pretrained_model)
    asr_model.encoder.unfreeze()
    asr_model.change_vocabulary(
      new_tokenizer_dir=cfg.model.tokenizer.dir,
      new_tokenizer_type=cfg.model.tokenizer.type
    )
    asr_model.setup_optimization(cfg.model.optim)
    asr_model.setup_training_data(cfg.model.train_ds)
    asr_model.setup_multiple_validation_data(cfg.model.validation_ds)
    asr_model.spec_augmentation = asr_model.from_config_dict(cfg.model.spec_augment)
    asr_model.set_trainer(trainer)
    trainer.fit(asr_model)
```

**Expected behavior**

WandB cfg should display the proper config ([Pastebin of the WandB config](https://pastebin.com/Bc29P9FL))

**Environment overview (please complete the following information)**

 - Environment location: Docker (nvcr.io/nvidia/pytorch:21.10-py3) on AWS EC2 using `docker run -it bash <image>`
 - Method of NeMo install: `pip install nemo_toolkit[asr]==1.5.1`

**Additional context**

GPU model: V100
Nvidia driver: 460

**Comment by titu1994** [comment]
In general, the set_trainer() should be the first call after creating the model - or pass the trainer in the restore_from() or from_pretrained() method itself. 

However this should not affect exp manager - the only thing it depends on is the config passed at this line `log_dir = exp_manager(trainer, cfg.get("exp_manager", None))`. Could you print out this config (cfg.exp_manager) and check whether it matches what you expect ?

**Comment by piraka9011** [comment]
My `exp_manager` cfg:

```yaml
exp_manager:
  exp_dir: "experiments"
  name: *name
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_wer"
    mode: "min"
    save_top_k: 2
    always_save_nemo: true
  create_wandb_logger: true
  wandb_logger_kwargs:
    job_type: train
    name: *name
    entity: $WANDB_ENTITY
    project: nemo-experiments
    tags: ["CitriNet-Lg", "train"]
```
