### ISSUE TITLE
Cannot export Fast Pitch models

### ISSUE THREAD

**Issue by juierror** [NVIDIA/NeMo#3705]
**Describe the bug**

I try to export fast pitch models, but it took a lot of RAM then process is killed. In my case, I use Mac OS to export and swap increase from 3 GB to 54 GB. I also used to try with google colab, but the kernel died after run export because memory issue.

**Steps/Code to reproduce bug**

```
from nemo.collections.tts.models import FastPitchModel

fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch")
fastpitch.export("fastpitch.onnx")
```

**Expected behavior**

The models can be exported to onnx

**Environment overview (please complete the following information)**

 - Environment location: Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
 - Method of NeMo install: pip install nemo_toolkit==1.6.2

**Environment details**

- OS version: MacOS 12.0.1
- PyTorch version: 1.10.1
- Python version: 3.8.9

Thank you

**Comment by Pongsasit** [comment]
Same issue with me running on,
AMD Ryzen 5 2600 Six-Core Processor
RAM 24 GB
(without any swap)

Environment details
    OS version: Ubuntu 18.0.4
    PyTorch version: 1.10.1
    Python version: 3.7.11
pip install nemo_toolkit==1.6.2


Thank you

**Comment by Oktai15** [comment]
Hello, @juierror @Pongsasit!

I can't get this error in `main` branch. 

```
In [1]: from nemo.collections.tts.models import FastPitchModel
In [2]: fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch")   
In [3]: fastpitch.export("fastpitch.onnx")
[NeMo I 2022-02-18 00:12:35 export_utils:250] Swapped 28 modules
[NeMo W 2022-02-18 00:12:35 nemo_logging:349] 
....
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
Out[3]: 
(['fastpitch.onnx'],
 ['nemo.collections.tts.models.fastpitch.FastPitchModel exported to ExportFormat.ONNX'])
```

**Comment by juierror** [comment]
> Hello, @juierror @Pongsasit!
> 
> I can't get this error in `main` branch.
> 
> ```
> In [1]: from nemo.collections.tts.models import FastPitchModel
> In [2]: fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch")   
> In [3]: fastpitch.export("fastpitch.onnx")
> [NeMo I 2022-02-18 00:12:35 export_utils:250] Swapped 28 modules
> [NeMo W 2022-02-18 00:12:35 nemo_logging:349] 
> ....
> Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
> Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
> Warning: Constant folding - Only steps=1 can be constant folded for opset >= 10 onnx::Slice op. Constant folding not applied.
> Out[3]: 
> (['fastpitch.onnx'],
>  ['nemo.collections.tts.models.fastpitch.FastPitchModel exported to ExportFormat.ONNX'])
> ```

Thank you very much for your quick reply. I test it again using main branch. However, I run with google colab instead this time with RAM 25.46 GB. It show `[NeMo I 2022-02-18 14:05:07 export_utils:250] Swapped 28 modules` before the kernel died.

```
## Install dependencies
!pip install wget
!apt-get install sox libsndfile1 ffmpeg
!pip install unidecode
!pip install matplotlib>=3.3.2

## Install NeMo
BRANCH = 'main'
!python -m pip install git+https://github.com/NVIDIA/NeMo.git@$BRANCH#egg=nemo_toolkit[all]

from nemo.collections.tts.models import FastPitchModel

fastpitch = FastPitchModel.from_pretrained("tts_en_fastpitch")
fastpitch.export("fastpitch.onnx")
```

I'm not sure, maybe I do something wrong. However, I will try again on MacOS. (At least I know someone can export it)

Thank you again.

This is the full log

```
[NeMo W 2022-02-18 14:04:52 optimizers:55] Apex was not found. Using the lamb or fused_adam optimizer will error out.
################################################################################
### WARNING, path does not exist: KALDI_ROOT=/mnt/matylda5/iveselyk/Tools/kaldi-trunk
###          (please add 'export KALDI_ROOT=<your_path>' in your $HOME/.profile)
###          (or run as: KALDI_ROOT=<your_path> python <your_script>.py)
################################################################################

[NeMo W 2022-02-18 14:04:53 __init__:23] `pynini` is not installed ! 
    Please run the `nemo_text_processing/setup.sh` scriptprior to usage of this toolkit.
[NeMo I 2022-02-18 14:04:55 cloud:66] Downloading from: https://api.ngc.nvidia.com/v2/models/nvidia/nemo/tts_en_fastpitch/versions/1.4.0/files/tts_en_fastpitch_align.nemo to /root/.cache/torch/NeMo/NeMo_1.7.0rc0/tts_en_fastpitch_align/b50e16c5d695b00855ae53d6ba4e4f7f/tts_en_fastpitch_align.nemo
[NeMo I 2022-02-18 14:05:01 common:704] Instantiating model from pre-trained checkpoint
[NeMo E 2022-02-18 14:05:03 vocabs:325] Torch distributed needs to be initialized before you initialized <nemo.collections.common.data.vocabs.Phonemes object at 0x7f180f83fbd0>. This class is prone to data access race conditions. Now downloading corpora from global rank 0. If other ranks pass this before rank 0, errors might result.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package cmudict to /root/nltk_data...
[nltk_data]   Package cmudict is already up-to-date!
[NeMo W 2022-02-18 14:05:06 modelPT:149] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    dataset:
      _target_: nemo.collections.asr.data.audio_to_text.AudioToCharWithPriorAndPitchDataset
      manifest_filepath: /raid/LJSpeech/nvidia_ljspeech_train.json
      max_duration: null
      min_duration: 0.1
      int_values: false
      normalize: true
      sample_rate: 22050
      trim: false
      sup_data_path: /raid/LJSpeech/prior
      n_window_stride: 256
      n_window_size: 1024
      pitch_fmin: 80
      pitch_fmax: 640
      pitch_avg: 211.27540199742586
      pitch_std: 52.1851002822779
      vocab:
        notation: phonemes
        punct: true
        spaces: true
        stresses: true
        add_blank_at: None
        pad_with_space: true
        chars: true
        improved_version_g2p: true
    dataloader_params:
      drop_last: false
      shuffle: true
      batch_size: 32
      num_workers: 12
    
[NeMo W 2022-02-18 14:05:06 modelPT:156] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s). 
    Validation config : 
    dataset:
      _target_: nemo.collections.asr.data.audio_to_text.AudioToCharWithPriorAndPitchDataset
      manifest_filepath: /raid/LJSpeech/nvidia_ljspeech_val.json
      max_duration: null
      min_duration: null
      int_values: false
      normalize: true
      sample_rate: 22050
      trim: false
      sup_data_path: /raid/LJSpeech/prior
      n_window_stride: 256
      n_window_size: 1024
      pitch_fmin: 80
      pitch_fmax: 640
      pitch_avg: 211.27540199742586
      pitch_std: 52.1851002822779
      vocab:
        notation: phonemes
        punct: true
        spaces: true
        stresses: true
        add_blank_at: None
        pad_with_space: true
        chars: true
        improved_version_g2p: true
    dataloader_params:
      drop_last: false
      shuffle: false
      batch_size: 32
      num_workers: 8
    
[NeMo I 2022-02-18 14:05:06 features:255] PADDING: 1
[NeMo I 2022-02-18 14:05:06 features:272] STFT using torch
[NeMo I 2022-02-18 14:05:07 save_restore_connector:157] Model FastPitchModel was successfully restored from /root/.cache/torch/NeMo/NeMo_1.7.0rc0/tts_en_fastpitch_align/b50e16c5d695b00855ae53d6ba4e4f7f/tts_en_fastpitch_align.nemo.
[NeMo I 2022-02-18 14:05:07 export_utils:250] Swapped 28 modules
```
