### ISSUE TITLE
Question : Conformer RNNT finetuning 

### ISSUE THREAD

**Issue by amejri** [NVIDIA/NeMo#3724]
Hi guys, 

I am trying to finetune STT En Conformer RNNT for spanish. the problem is the following : when I try to change the tokenizer, the model is just such as training from scratch and it takes too much time for converging ( in reality it doesn't converge :p ). Does any one have an explanation, an idea or a trick to bypass this problem.

With best regards,

**Comment by eesungkim** [comment]
Hi @amejri,

In case of changing the tokenizer, especially, the number of BPE, we should exclude the weights and bias of part of the network when we load weights of pretrained model. For example, I'm finetuning the conformer-transducer model by adding the following contents to the yaml file like this:

NeMo/examples/asr/conf/conformer/conformer_transducer_bpe.yaml
```
name: "Conformer-Transducer-BPE"
init_from_nemo_model:
  model:
    path: /Users/eesungkim/pretrained_model/nemo_asr_set/stt_en_conformer_transducer_small.nemo 
    exclude: ["decoder.prediction.embed.weight","joint.joint_net.2.weight","joint.joint_net.2.bias"]
model:
  sample_rate: &sample_rate 16000
  compute_eval_loss: false 
  log_prediction: true 
  ctc_reduction: mean_batch

...
```
