### ISSUE TITLE
problem of load ASR lstm trained model

### ISSUE THREAD

**Issue by sarasesar** [NVIDIA/NeMo#4514]
hello. I have train a "LSTM-Transducer-BPE" model some days ago. and to save the model, I have used checkpoint. for this train, I have used the default config.
after that, when i want to load this model by `EncDecRNNTBPEModel` method,

i got an error and i could not use this model:
```
RuntimeError: Error(s) in loading state_dict for EncDecRNNTBPEModel:
	Missing key(s) in state_dict: "decoder.prediction.dec_rnn.lstm.weight_hr_l0", "decoder.prediction.dec_rnn.lstm.weight_hr_l1". 
	size mismatch for decoder.prediction.dec_rnn.lstm.weight_ih_l0: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([8192, 640]).
	size mismatch for decoder.prediction.dec_rnn.lstm.weight_hh_l0: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([8192, 640]).
	size mismatch for decoder.prediction.dec_rnn.lstm.bias_ih_l0: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([8192]).
	size mismatch for decoder.prediction.dec_rnn.lstm.bias_hh_l0: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([8192]).
	size mismatch for decoder.prediction.dec_rnn.lstm.weight_ih_l1: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([8192, 640]).
	size mismatch for decoder.prediction.dec_rnn.lstm.weight_hh_l1: copying a param with shape torch.Size([2560, 640]) from checkpoint, the shape in current model is torch.Size([8192, 640]).
	size mismatch for decoder.prediction.dec_rnn.lstm.bias_ih_l1: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([8192]).
	size mismatch for decoder.prediction.dec_rnn.lstm.bias_hh_l1: copying a param with shape torch.Size([2560]) from checkpoint, the shape in current model is torch.Size([8192]).
```
please help me.
thank you.

**Comment by titu1994** [comment]
Could you post the code to load the model (I assume Nemo model)? It seems that the checkpoint has weights for an encoder with hidden dim 2560 but is trying to load into a model with hidden dim 8192. As I recall lstm weights are 4*hidden_dim so seems the new model has a lot larger hidden dim. 

Fyi @VahidooX

**Comment by sarasesar** [comment]
```

**Comment by sarasesar** [comment]
I tried to load model by `nemo.collections.asr.EncDecRNNTBPEModel.restore_from()` method. and also I tried to load the model by using several versions of Nemo such as 1.7.2, 1.8.2, and 1.9.0. But I could not load model.


I have train the model by this config :
```
  encoder:
    _target_: nemo.collections.asr.modules.RNNEncoder
    feat_in: ${model.preprocessor.features}
    n_layers: 8
    d_model: 2048
    proj_size: ${model.model_defaults.pred_hidden} # you may set it if you need different output size other than the default d_model
    rnn_type: "lstm" # it can be lstm, gru or rnn
    bidirectional: False
```
How can I fix it? 
thank you.

**Comment by titu1994** [comment]
Config seems fine but this isn't the decoder config, can you post the full config ? And if possible the code/script being used to load the model.

**Comment by sarasesar** [comment]
thank you. sure, of course.
decoder config was: 
```
  decoder:
    _target_: nemo.collections.asr.modules.RNNTDecoder
    normalization_mode: null 
    random_state_sampling: false 
    blank_as_pad: true
    prednet:
      pred_hidden: ${model.model_defaults.pred_hidden}=640
      pred_rnn_layers: 2
      t_max: null
      dropout: 0.2
      rnn_hidden_size: 2048

  joint:
    _target_: nemo.collections.asr.modules.RNNTJoint
    log_softmax: null 
    preserve_memory: false  

    fuse_loss_wer: true
    fused_batch_size: 16

    jointnet:
      joint_hidden: ${model.model_defaults.joint_hidden}=640
      activation: "relu"
      dropout: 0.2

  decoding:
    strategy: "greedy" 
    # greedy strategy config
    greedy:
      max_symbols: 10

    # beam strategy config
    beam:
      beam_size: 50
      return_best_hypothesis: True
      score_norm: true
      tsd_max_sym_exp: 50 
      alsd_max_target_len: 2.0  
```
and my code for load the model is:
```
import nemo.collections.asr as nemo_asr
model = nemo_asr.models.EncDecRNNTBPEModel.restore_from('lstm_mymodel.nemo') 
```
