### ISSUE TITLE
Testing a pre-trained model

### ISSUE THREAD

**Issue by carlosfranzreb** [NVIDIA/NeMo#4655]
Hello,

I am trying to test a pre-trained conformer transducer, but the reported WER is around 100 %, whereas it is much lower when I use the `transcribe()` method of the model and compute the WER myself. What am I doing wrong?

Script:

```python
import yaml
from nemo.collections.asr.models.rnnt_bpe_models import EncDecRNNTBPEModel
import pytorch_lightning as pl

trainer = pl.Trainer(devices=1, accelerator="gpu", max_epochs=50)
config = yaml.load(open("./config/config.yaml"), Loader=yaml.FullLoader)
ct = EncDecRNNTBPEModel.from_pretrained("stt_de_conformer_transducer_large")

ct.setup_test_data(config["data"]["test_ds"])
trainer.test(ct, dataloaders=ct.test_dataloader())
```

Config file:
```yaml
data:
    test_ds:
    manifest_filepath: data/train_split/debug.txt
    sample_rate: 48000
    batch_size: 1
    shuffle: false
    num_workers: 0
    pin_memory: true
    use_start_end_token: false
```
