### ISSUE TITLE
[TTS][German][Single Speaker] Generated audio far away from original Thorsten voice  

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [NVIDIA/NeMo#4868]
**Describe the bug**

Using the main branch of Nemo and TTS inference with Fastpitch and Hifigan  /  German single speaker model results in bad audio. 

**Steps/Code to reproduce bug**

git clone https://github.com/NVIDIA/NeMo/
cd NeMo
python3.8 -m venv venv
source venv/bin/activate
pip3 install a-lot-of-missing-requirements when executing
python3 tts_german.py where inference code is as follows tts_german.py

```
import soundfile as sf
from nemo.collections.tts.models.base import SpectrogramGenerator, Vocoder

# Download and load the pretrained fastpitch model
spec_generator = SpectrogramGenerator.from_pretrained(model_name="tts_de_fastpitch_singlespeaker")#.cuda()
# Download and load the pretrained hifigan model
vocoder = Vocoder.from_pretrained(model_name="tts_de_hui_hifigan_ft_fastpitch_multispeaker_5")#.cuda()

# All spectrogram generators start by parsing raw strings to a tokenized version of the string
parsed = spec_generator.parse("In den alten Zeiten, wo das Wünschen noch geholfen hat, lebte ein König, dessen Töchter waren alle schön.")
# They then take the tokenized string and produce a spectrogram
spectrogram = spec_generator.generate_spectrogram(tokens=parsed)
# Finally, a vocoder converts the spectrogram to audio
audio = vocoder.convert_spectrogram_to_audio(spec=spectrogram)

# Save the audio to disk in a file called speech.wav
# Note vocoder return a batch of audio. In this example, we just take the first and only sample.
sf.write("speech.wav", audio.to('cpu').detach().numpy()[0], 44100)
```

**Expected behavior**

Good audio

**Environment overview (please complete the following information)**

See above

**Environment details**

See above

**Additional context**

Audio sample [https://sndup.net/hxnz/](https://sndup.net/hxnz/)

**Comment by eqikkwkp25-cyber** [comment]
@XuesongYang Thanks for looking into this. There is definitely something about the rate used but with 22050 Hz it does not sound better at all. 

Audio sample [Nemo Thorsten Sample 22050](https://sndup.net/nxfd/)

As i cannot find a reopen button, can you pleas e reopen for analyzing? 

Code used:
```
import soundfile as sf
from nemo.collections.tts.models.base import SpectrogramGenerator, Vocoder

# Download and load the pretrained fastpitch model
spec_generator = SpectrogramGenerator.from_pretrained(model_name="tts_de_fastpitch_singlespeaker")#.cuda()
# Download and load the pretrained hifigan model
vocoder = Vocoder.from_pretrained(model_name="tts_de_hui_hifigan_ft_fastpitch_multispeaker_5")#.cuda()

# All spectrogram generators start by parsing raw strings to a tokenized version of the string
parsed = spec_generator.parse("In den alten Zeiten, wo das Wünschen noch geholfen hat, lebte ein König, dessen Töchter waren alle schön.")
# They then take the tokenized string and produce a spectrogram
spectrogram = spec_generator.generate_spectrogram(tokens=parsed)
# Finally, a vocoder converts the spectrogram to audio
audio = vocoder.convert_spectrogram_to_audio(spec=spectrogram)

# Save the audio to disk in a file called speech.wav
# Note vocoder return a batch of audio. In this example, we just take the first and only sample.
sf.write("speech.wav", audio.to('cpu').detach().numpy()[0], 22050)
```

**Comment by eqikkwkp25-cyber** [comment]
Can you check the model_config.yaml and used sample_rate for fastpitch on your side @XuesongYang ? For me it downloads the model to 

`.cache/torch/NeMo/NeMo_1.12.0rc0/tts_de_fastpitch_align/8f232e067b0b94b03191b3206322b34a/tts_de_fastpitch_align.nemo`

and uses 22050, see the content of the model config

```
learn_alignment: true
bin_loss_warmup_epochs: 100
n_speakers: 1
max_token_duration: 75
symbols_embedding_dim: 384
pitch_embedding_kernel_size: 3
pitch_fmin: 65.40639132514966
pitch_fmax: 2093.004522404789
pitch_mean: 132.524658203125
pitch_std: 37.389366149902344
sample_rate: 22050
n_mel_channels: 80
n_window_size: 1024
n_window_stride: 256
n_fft: 1024
lowfreq: 0
highfreq: 8000
window: hann
text_normalizer:
  _target_: nemo_text_processing.text_normalization.normalize.Normalizer
  lang: de
  input_case: cased
  whitelist: nemo:60f9de025bd145bdb54ba79d91f9449d_whitelist.tsv
text_normalizer_call_kwargs:
  verbose: false
  punct_pre_process: true
  punct_post_process: true
text_tokenizer:
  _target_: nemo.collections.tts.torch.tts_tokenizers.GermanCharsTokenizer
  punct: true
  apostrophe: true
  pad_with_space: true
train_ds:
  dataset:
    _target_: nemo.collections.tts.torch.data.TTSDataset
    manifest_filepath: /Data/openslr-95-german-neutral-tts/thorsten-de/train_phonemes_manifest.json
    sample_rate: 22050
    sup_data_path: /Data/openslr-95-german-neutral-tts/thorsten-de/phonemes5/
    sup_data_types:
    - align_prior_matrix
    - pitch
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    window: hann
    n_mels: 80
    lowfreq: 0
    highfreq: 8000
    max_duration: 14
    min_duration: 0.1
    ignore_file: null
    trim: false
    pitch_fmin: 65.40639132514966
    pitch_fmax: 2093.004522404789
    pitch_norm: true
    pitch_mean: 132.524658203125
    pitch_std: 37.389366149902344
  dataloader_params:
    drop_last: false
    shuffle: true
    batch_size: 32
    num_workers: 12
validation_ds:
  dataset:
    _target_: nemo.collections.tts.torch.data.TTSDataset
    manifest_filepath: /Data/openslr-95-german-neutral-tts/thorsten-de/val_phonemes_manifest.json
    sample_rate: 22050
    sup_data_path: /Data/openslr-95-german-neutral-tts/thorsten-de/phonemes5/
    sup_data_types:
    - align_prior_matrix
    - pitch
    n_fft: 1024
    win_length: 1024
    hop_length: 256
    window: hann
    n_mels: 80
    lowfreq: 0
    highfreq: 8000
    max_duration: null
    min_duration: 0.1
    ignore_file: null
    trim: false
    pitch_fmin: 65.40639132514966
    pitch_fmax: 2093.004522404789
    pitch_norm: true
    pitch_mean: 132.524658203125
    pitch_std: 37.389366149902344
  dataloader_params:
    drop_last: false
    shuffle: false
    batch_size: 32
    num_workers: 2
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  features: 80
  lowfreq: 0
  highfreq: 8000
  n_fft: 1024
  n_window_size: 1024
  window_size: false
  n_window_stride: 256
  window_stride: false
  pad_to: 1
  pad_value: 0
  sample_rate: 22050
  window: hann
  normalize: null
  preemph: null
  dither: 0.0
  frame_splicing: 1
  log: true
  log_zero_guard_type: add
  log_zero_guard_value: 1.0e-05
  mag_power: 1.0
input_fft:
  _target_: nemo.collections.tts.modules.transformer.FFTransformerEncoder
  n_layer: 6
  n_head: 1
  d_model: 384
  d_head: 64
  d_inner: 1536
  kernel_size: 3
  dropout: 0.1
  dropatt: 0.1
  dropemb: 0.0
  d_embed: 384
output_fft:
  _target_: nemo.collections.tts.modules.transformer.FFTransformerDecoder
  n_layer: 6
  n_head: 1
  d_model: 384
  d_head: 64
  d_inner: 1536
  kernel_size: 3
  dropout: 0.1
  dropatt: 0.1
  dropemb: 0.0
alignment_module:
  _target_: nemo.collections.tts.modules.aligner.AlignmentEncoder
  n_text_channels: 384
duration_predictor:
  _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
  input_size: 384
  kernel_size: 3
  filter_size: 256
  dropout: 0.1
  n_layers: 2
pitch_predictor:
  _target_: nemo.collections.tts.modules.fastpitch.TemporalPredictor
  input_size: 384
  kernel_size: 3
  filter_size: 256
  dropout: 0.1
  n_layers: 2
optim:
  name: adamw
  lr: 0.1
  betas:
  - 0.9
  - 0.98
  weight_decay: 1.0e-06
  sched:
    name: NoamAnnealing
    warmup_steps: 1000
    last_epoch: -1
    d_model: 1
target: nemo.collections.tts.models.fastpitch.FastPitchModel
nemo_version: 1.9.0rc0
```
