### ISSUE TITLE
megatron_lm_ckpt_to_nemo.py  and the hparams.yaml

### ISSUE THREAD

**Issue by grzywada** [NVIDIA/NeMo#4993]
The example at the top of megatron_lm_ckpt_to_nemo.py  sugests that you can convert the megatron-lm checkpoint without hparams.yaml file. I did not spend huge amount of time trying to understand this code but its seems not possible and the only reason why hparams is not a manadatory argument seems to be because one can optionally pass cnf via kwargs.

Could we add literally one sentence describing that in the top of the file preferably also providing an example of a yaml file - happy to send out working 5B example for GPT.

**Comment by okuchaiev** [comment]
@yidong72 , can you please have a look at this?

**Comment by yidong72** [comment]
The `hparams.yaml` file is required to run the converstion. `hparams.yaml` usually is generated by pytorch lightninig when running the training job. It is the model section of the model pretraining conf with an extra `cfg` key. 
Here is one example for 40B GPT

```yaml
cfg:                                                                                                                                                                                                                                                                                         
  micro_batch_size: 4                                                                                                                                                                                                                                                                        
  global_batch_size: 8                                                                                                                                                                                                                                                                       
  tensor_model_parallel_size: 8                                                                                                                                                                                                                                                              
  pipeline_model_parallel_size: 2                                                                                                                                                                                                                                                            
  encoder_seq_length: 2048                                                                                                                                                                                                                                                                   
  max_position_embeddings: 2048                                                                                                                                                                                                                                                              
  num_layers: 48                                                                                                                                                                                                                                                                             
  hidden_size: 8192                                                                                                                                                                                                                                                                          
  ffn_hidden_size: 32768                                                                                                                                                                                                                                                                     
  num_attention_heads: 64                                                                                                                                                                                                                                                                    
  init_method_std: 0.02                                                                                                                                                                                                                                                                      
  hidden_dropout: 0.1                                                                                                                                                                                                                                                                        
  kv_channels: null                                                                                                                                                                                                                                                                          
  apply_query_key_layer_scaling: true                                                                                                                                                                                                                                                        
  layernorm_epsilon: 1.0e-05                                                                                                                                                                                                                                                                 
  make_vocab_size_divisible_by: 128
  pre_process: true                                                                                                                                                                                                                                                                          
  post_process: true                                                                                                                                                                                                                                                                         
  persist_layer_norm: true                                                                                                                                                                                                                                                                   
  gradient_as_bucket_view: true                                                                                                                                                                                                                                                              
  tokenizer:                                                                                                                                                                                                                                                                                   
    library: megatron                                                                                                                                                                                                                                                                          
    type: GPT2BPETokenizer                                                                                                                                                                                                                                                                     
    model: null                                                                                                                                                                                                                                                                                
    vocab_file: models/gpt2-vocab.json                                                                                                                                                                                                                                                         
    merge_file: models/gpt2-merges.txt                                                                                                                                                                                                                                                       
  native_amp_init_scale: 4294967296                                                                                                                                                                                                                                                          
  native_amp_growth_interval: 1000                                                                                                                                                                                                                                                           
  hysteresis: 2                                                                                                                                                                                                                                                                              
  fp32_residual_connection: false                                                                                                                                                                                                                                                            
  fp16_lm_cross_entropy: false                                                                                                                                                                                                                                                               
  megatron_amp_O2: false                                                                                                                                                                                                                                                                     
  fp32_grad_accum: false                                                                                                                                                                                                                                                                     
  contiguous_grad_bucket: false                                                                                                                                                                                                                                                              
  async_grad_allreduce: false               
...
```
