### ISSUE TITLE
VAD max duration parameters?

### ISSUE THREAD

**Issue by mesutToruk** [NVIDIA/NeMo#5130]
Are there any parameter to set max segment duration? I saw some segments can be so long. And when i listened to wav, i can see that there is some silence part. However, VAD does not split these areas.
For example;
```
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 0.73, "duration": 1.27, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 3.21, "duration": 0.71, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 5.05, "duration": 0.71, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 6.81, "duration": 1.67, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 9.93, "duration": 4.55, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 15.21, "duration": 0.95, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 17.69, "duration": 0.39, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 18.81, "duration": 2.07, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 21.77, "duration": 13.67, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 36.57, "duration": 15.67, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 53.05, "duration": 0.87, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 55.45, "duration": 1.59, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 58.17, "duration": 18.95, "label": "UNK", "uniq_id": "arda", "text": "-"}
{"audio_filepath": "/media/mesut/Tosun/ses/NeMo/tools/asr_webapp/arda.wav", "offset": 77.93, "duration": 76.31, "label": "UNK", "uniq_id": "arda", "text": "-"}
```
My VAD parameters;
```
vad:
    model_path: "vad_multilingual_marblenet" #.nemo local model path or pretrained model name or none
    parameters: # Parameters were tuned on 0~20db SNR noisy and clean multilingual ASR data.
      normalize_audio: False
      window_length_in_sec: 0.63  # window length in sec for VAD context input
      shift_length_in_sec: 0.08 # shift length in sec for generate frame level VAD prediction, Here we use 0.08 for faster inferene
      smoothing: False # false or type of smoothing method (eg: median, mean)
      overlap: 0.5 # overlap ratio for overlapped mean/median smoothing filter. If smoothing=False, ignore this value.
      postprocessing:
        onset: 0.95 # onset threshold for detecting the beginning and end of a speech
        offset: 2.0 # offset threshold for detecting the end of a speech.
        pad_onset: 0.15 # adding durations before each speech segment
        pad_offset: 0.15 # adding durations after each speech segment
        min_duration_on: 0.2 # threshold for small non_speech deletion
        min_duration_off: 0.6 # threshold for short speech segment deletion
        filter_speech_first: True 
```
