### ISSUE TITLE
How do I save all checkpoints in exp_manager

### ISSUE THREAD

**Issue by stas00** [NVIDIA/NeMo#7514]
**Describe the bug**

I'm trying to accomplish a seemingly trivial task of saving all checkpoints during training - many hours later after trying many different configurations I still can't do and I see multiple problems

**Steps/Code to reproduce bug**

Here is the relevant part of the config:
```
trainer:
  enable_checkpointing: False # checkpointing provided by exp_manager
  limit_val_batches: 0
  limit_test_batches: 0
exp_manager:
  checkpoint_callback_params:
    every_n_train_steps: 5
    every_n_epochs: null
    monitor: null # want all checkpoints, 
    save_top_k: -1 # save all checkpoints
    save_last: True
```

The main doc in PTL is https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.ModelCheckpoint.html#modelcheckpoint

There are multiple problems here, but the key is to get rid of the message as I'm not running eval - only training and be able to save all checkpoints. The message that I get is:

```
Epoch 0, global step 10: '' was not in top -1
```
The PL doc says:
> monitor (Optional[str]) – quantity to monitor. By default it is None which saves a checkpoint only for the last epoch.

 if I set it to null it breaks:
 
```
nemo/nemo/utils/exp_manager.py", line 889, in configure_checkpointing
    if "val" in params.monitor:
TypeError: argument of type 'NoneType' is not iterable
```

and looking at PL's source code:

```
    def _save_topk_checkpoint(self, trainer: "pl.Trainer", monitor_candidates: Dict[str, Tensor]) -> None:
        if self.save_top_k == 0:
            return

        # validate metric
        if self.monitor is not None:
            if self.monitor not in monitor_candidates:
```
it shouldn't go into validation metric if it's set to None, but NeMo doesn't allow me to do that.

Then the PL doc says:
> save_top_k
> (int) – if save_top_k == k, the best k models according to the quantity monitored will be saved. if save_top_k == 0, no models are saved. if save_top_k == -1, all models are saved. Please note that the monitors are checked every every_n_epochs epochs. if save_top_k >= 2 and the callback is called multiple times inside an epoch, the name of the saved file will be appended with a version count starting with v1.

but I still get only the last checkpoint saved, 

and this message:

```
Epoch 0, global step 10: 'blah' was not in top -1
```
looks wrong because it shouldn't even go there, as it's set to -1 == meaning do not check.

**Expected behavior**

I need to be able:

1. save all checkpoints
2. while not running eval

Thank you!

**Comment by titu1994** [comment]
Passing arbitrary arguments to exp Manager will not work. It does not support passing null to monitor. Save top k of -1 must be a relatively new thing, never used it before. But if ptl supports it, that's good enough I guess. 

You can set your monitor to "loss" or "train_loss" - that should work fine I think. 

Worst comes to worst, set top k to the number of epochs itself is another option but I don't think that's needed, -1 should be fine.

**Comment by stas00** [comment]
> Passing arbitrary arguments to exp Manager will not work.

Why is it arbitrary? 

I tried your suggestion, but I couldn't make them work:

1. Tried:

```
    monitor: "loss" 
    save_top_k: -1
```
saves only the last checkpoint and warns:
```
Epoch 0, global step 5: 'loss' was not in top -1
[NeMo I 2023-09-27 02:27:59 nlp_overrides:251] Removing checkpoint: exp_manager/megatron_retro/checkpoints/mp_rank_00/megatron_retro--val_loss=0.00-step=5-consumed_samples=20.0-last.ckpt
``````

2. Tried:

```
    monitor: "loss" 
    save_top_k: 10000
```
same problem
```
Epoch 0, global step 5: 'loss' was not in top 10000
[NeMo I 2023-09-27 02:27:59 nlp_overrides:251] Removing checkpoint: exp_manager/megatron_retro/checkpoints/mp_rank_00/megatron_retro--val_loss=0.00-step=5-consumed_samples=20.0-last.ckpt
```

**Comment by titu1994** [comment]
Agreed my bad and,  not arbitrary then. I'm not updated with all the changes in ptl 2. Vague docstring indeed. 

What I'm more surprised by, your loss is 0. I think there's bigger problems than just checkpoint saving.

**Comment by titu1994** [comment]
I think let's get some expert in retro to help out. @yidong72

**Comment by stas00** [comment]
I mean it should be as simple as:

```
  checkpoint_callback_params:
    every_n_train_steps: 5
    save_top_k: -1 # save all models
``` 
So that I set a flag to save all models and indicate how often it should be saved.

but it doesn't work. 

and why would one need to monitor anything if it's already set to save all checkpoints?

Comparing with my colleague's setup it appears that one can't not run validation and get all checkpoints saved, I'm able to hack around with:

```
trainer:
  val_check_interval: 5
  limit_val_batches: 1
  limit_test_batches: 0
  checkpoint_callback_params:
    monitor: "step" # want all checkpoints, and nemo breaks PTL here
    save_top_k: -1 # save all models
    mode: max      
```

But now it saves some checkpoints and not all:

```
step=1.ckpt
step=2.ckpt
step=3.ckpt
step=5.ckpt
step=6.ckpt
step=7.ckpt
step=8.ckpt
step=10.ckpt
step=11.ckpt
step=12.ckpt
step=13.ckpt
step=15.ckpt
step=16.ckpt
```
as you can see mysteriously 4 and 14 are missing

The message is difficult to make sense of
```
Epoch 0, global step 5: 'step' reached 5.00000 (best 5.00000), saving model to 'exp_manager/megatron_retro/checkpoints/step=5.ckpt' as top 4
```
but I guess we are now choosing the "best" step?

I'm very very lost. Would love your support or docs if you have any to overcome this. (2 days at it already)

Thank you!

**Comment by titu1994** [comment]
Does PTL have any test or example that combined all these args or shows what set of flags you gotta combine to save every model? This is not a use case in NeMo, models are huge, we'd mostly stick to top 5 at best.

**Comment by stas00** [comment]
re: such examples - Not that I know off, but I could be wrong as I'm new to PTL.

We need to save/keep all checkpoints because we run lm-harness on each checkpoint asynchronously and doing eval during training is pointless since it gives very little signal and just wastes compute and delays finish line. and trust me our models are huge too ;)

**Comment by titu1994** [comment]
Haha I'm surprised. Won't you run out of ssd space with just 5-10 checkpoints saved at that point then ? Well in either case, let's see if PTL can help wrt this

**Comment by stas00** [comment]
During BLOOM training we had an insane luxury of having 300TB of insanely fast GPFS (Jean Zay HPC) - amazing! This one was Megatron-Deepspeed training.

For IDEFICS-80B we had no such luxury and only some 10TB of disc space - so we built an asynchronous set of independent slurm jobs that would eval, convert to a different format, sync to s3,  and cleanup - so we only ever had 2-4 checkpoints at any given time. It actually worked amazingly well. This one was Deepspeed ZeRO3 training.

**Comment by stas00** [comment]
Thank you for the example, @awaelchli 

The issue is that it fails in NeMo, whereas your example is of a pure PTL.

Using:
```
  checkpoint_callback_params:
    every_n_train_steps: 5
    every_n_epochs: null
    save_top_k: -1 # save all models
    save_last: True
```
deletes all checkpoints but the last one. It doesn't respect `save_top_k: -1`

PTL-2.0.9, and Nemo@HEAD

-----------------------

and there are multiple other issues:

I can't say:
```
    every_n_train_steps: 5
```
it crashes with `Combination of parameters every_n_train_steps=5, every_n_epochs=1 and train_time_interval=None should be mutually exclusive.` but I haven't specified `every_n_epochs` anywhere.

I have to say:
```
    every_n_train_steps: 5
    every_n_epochs: null
```
which sounds broken.

2. Even though I don't want to monitor anything and don't specify `monitor` I still get:
```
merlion-ultra-ghpc-60:0]:Epoch 0, global step 15: 'val_loss' was not in top -1
```
and what does it even mean? `not in top -1`?

**Comment by titu1994** [comment]
We're subclassing the checkpoint callback, probably something in the 2.0 update needs to be manually merged with our version to get all the newer functionality to work properly. We'll take a look but for the time being no ETA.

**Comment by stas00** [comment]
For posterity after many tries I found this hack to work to save all checkpoints and not run eval:

```
 trainer:
  val_check_interval: 1000000000000000000000 # we don't want validation
  limit_val_batches: null
  limit_test_batches: null
exp_manager:
  checkpoint_callback_params:
    every_n_train_steps: 10
    every_n_epochs: null # must be set to null to use every_n_train_steps
    monitor: "step" # want all checkpoints, so step + mode: max always succeeds
    mode: max
    save_top_k: -1 # save all models
    save_last: True
```

The other problem I found that each checkpoint is saved twice!
https://github.com/Lightning-AI/lightning/issues/18670
