### ISSUE TITLE
OOM killed when diarizing 4 hours recording

### ISSUE THREAD

**Issue by tttalshaul** [NVIDIA/NeMo#8235]
I'm trying nemo_toolkit 1.22.0 on T4 (14G vRAM) with 40G cpu RAM to diarize with ClusteringDiarizer. 
After completing speaker embeddings, tqdm shows "clustering: 0%" and then my script is getting killed by OS with error 137 OOM (out of memory) because of RAM consumption greater then 40G..

Installed nemo using pip install nemo_toolkit==1.22.0 (python 3.10 x64) on premise K8S.

I'm using diar_infer_meeting.yaml with max_num_speakers=20, chunk_cluster_count=50,
Tried to lower embeddings_per_chunk from default 10000 to 500 but it didn't help.

**Comment by nithinraok** [comment]
@tttalshaul can you share more info on length of audio and size of embeddings in pkl file you saved?

**Comment by tttalshaul** [comment]
Audio length is 3:43 hours after cutting silence (using VAD). 
embeddings:
scale0 6.6M len 8920
scale1 7.9M len 10704
scale2 9.9M len 13385
scale3 14M len 17846
scale4 20M len 26772
scale5 40M len 53548

**Comment by tttalshaul** [comment]
@nithinraok 
What tests can I make to understand the cause of this problem?

I'm moving ClusteringDiarizer(cfg=cfg).to(device), and I see that device is cuda:0. 
I understand that this only effects vad and embeddings extraction, but clustering occurs in cpu RAM anyway?

Thank you

**Comment by nithinraok** [comment]
@tango4j what is the maximum audio duration we currently support for single pass offline diarzation

**Comment by tango4j** [comment]
@tttalshaul 

Sorry for the late reply.
If you have visible cuda devices, both embedding extractions and clustering will be happening on GPU RAM.

```
clustering: 
    parameters:
....
      chunk_cluster_count: 50 # Number of forced clusters (overclustering) per unit chunk in long-form audio clustering.
      embeddings_per_chunk: 10000 # Number of embeddings in each chunk for long-form audio clustering. Adjust based on GPU memory capacity. (default: 10000, approximately 40 mins of audio) 
```
You should **increase** the `embeddings_per_chunk` value to consume less amount of memory.
Also note that even if you use long form audio clustering, there is a limit of audio length.
Thus, you need to make a compromise between performance and length. 
Increasing `embeddings_per_chunk` will consume less memory but could lead to deteriorated performance.
